# Generated by Django 3.1.8 on 2021-05-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pluckyblog', '0005_auto_20210506_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='comment',
        ),
    ]
