# Generated by Django 3.1.8 on 2021-05-06 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluckyblog', '0006_auto_20210506_2256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_connected',
            new_name='post',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
