# Generated by Django 3.1.8 on 2021-05-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pluckyblog', '0007_auto_20210506_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
